# Generated by Django 5.2.3 on 2025-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
